Repository pyronear/pyro-platform, pull requests merged in 2020-12, with the labels that each got.

#23 feat : Added new markers types and live alerts features
  app/alerts.py
  app/homepage.py
  app/main.py
  app/navbar.py
  app/utils.py
Labels: enhancement, topic: core platform features

#26 Adding caching decorator to cache and reuse heavy data
  .gitignore
  app/main.py
  app/utils.py
  requirements.txt
Labels: enhancement, topic: core platform features

#29 feat: Added support of API interaction within the web-app
  .github/workflows/main.yml
  Dockerfile
  README.md
  app/config.py
  app/services/__init__.py
  app/services/api.py
  docker-compose.yml
  requirements.txt
Labels: documentation, enhancement, topic: api, topic: build

#30 fix: Fixed non-docker running of the Flask server
  .github/workflows/main.yml
  README.md
  app/config.py
  requirements.txt
Labels: bug, topic: build

#31 feat: fetching alert data from pyroclient api
  app/alerts.py
  app/homepage.py
  app/main.py
Labels: enhancement, topic: api

#32 fix: Fixed gunicorn process on Heroku
  .github/workflows/main.yml
  app/main.py
Labels: bug, topic: build

#33 Alert acknowledgement
  app/alerts.py
  app/main.py
  app/utils.py
  requirements.txt
Labels: bug, enhancement

#34 Using real calculated risk scores for each department to be displayed on the map
  app/assets/up_arrow_png.png
  app/config.py
  app/risks.py
Labels: enhancement, topic: core platform features, topic: pyrorisk
