Repository pyronear/pyro-platform, pull requests merged in 2020-10, with the labels that each got.

#1 Adding the basic repo architecture
  .github/workflows/pythonpackage.yml
  .gitignore
  Makefile
  pyronear-webapp/app.py
  requirements.txt
  tests/app_test.py
Labels: topic: build

#3 feat: Set up dockerized server for the dash app
  .flake8
  .github/workflows/main.yml
  .github/workflows/pythonpackage.yml
  Dockerfile
  Makefile
  README.md
  app/alerts.py
  app/config.py
  app/data/cameras.csv
  app/data/departements.geojson
  app/homepage.py
  app/index.py
  app/navbar.py
  app/risks.py
  app/utils.py
  docker-compose.yml
  pyronear-webapp/alerts.py
  pyronear-webapp/homepage.py
  pyronear-webapp/navbar.py
  pyronear-webapp/risks.py
  requirements.txt
  tests/app_test.py
Labels: documentation, enhancement, topic: build

#5 feat: Sets the project for automatic deployment on Heroku
  Procfile
  app/alerts.py
  app/main.py
  app/risks.py
  docker-compose.yml
  requirements.txt
Labels: enhancement, topic: build

#7 graphs.py new file + some changes in homepage.py layout !
  app/graphs.py
  app/homepage.py
Labels: enhancement

#8 Added the slider and the callback for interactivity
  app/main.py
  app/risks.py
  app/utils.py
Labels: enhancement

#9 Adding basic cameras information when hovered on map
  app/alerts.py
  app/main.py
  app/utils.py
Labels: enhancement
