Repository pyronear/pyro-platform, pull requests merged in 2021-03, with the labels that each got.

#40 chore: Updated license from GPLv3 to Apache 2.0
  .github/workflows/main.yml
  LICENSE
  README.md
  app/alerts.py
  app/config.py
  app/graphs.py
  app/homepage.py
  app/main.py
  app/navbar.py
  app/risks.py
  app/services/api.py
  app/utils.py
  test/test_headers.py
Labels: documentation, topic: build

#39 Fetching GeoJSON file from Pyro-Risk release
  app/alerts.py
  app/config.py
  app/data/departements.geojson
  app/risks.py
Labels: enhancement

#42 Alert screen for CODIS operational room
  .gitignore
  app/alert_screen.py
  app/assets/pyro_alert_off.png
  app/assets/pyro_alert_on.png
  app/assets/pyro_fire_logo.png
  app/assets/styles.css
  app/homepage.py
  app/main.py
  app/navbar.py
  app/utils.py
Labels: enhancement, topic: core platform features

#44 Fix issue on alert screen
  app/main.py
Labels: bug

#45 revert to where master was before #44
  app/main.py
Labels: bug
