Repository pyronear/pyro-platform, pull requests merged in 2021-05, with the labels that each got.

#50 Import fix to deploy
  app/alerts.py
Labels: bug

#52 fix: Update websocket to https
  .github/workflows/docker_publish.yaml
  .github/workflows/main.yml
  app/homepage.py
Labels: bug, topic: build

#54 Alert erasing button
  app/alerts.py
  app/homepage.py
  app/main.py
Labels: enhancement
