Repository pyronear/pyro-platform, pull requests merged in 2021-04, with the labels that each got.

#43 Login
  .github/workflows/main.yml
  .gitignore
  Dockerfile
  README.md
  app/alerts.py
  app/assets/background.png
  app/config.py
  app/data/login_correspondences.enc
  app/homepage.py
  app/main.py
  requirements.txt
Labels: enhancement

#46 Fix latest issues with Dockerfile
  Dockerfile
  app/main.py
  docker-compose.yml
Labels: bug

#47 Login via api
  .github/workflows/main.yml
  Dockerfile
  README.md
  app/data/group_correspondences.json
  app/data/login_correspondences.enc
  app/main.py
  requirements.txt
Labels: enhancement

#48 feat: New alert flow and websocket acting as a webhook to handle alerts date sent by API
  .github/workflows/main.yml
  Procfile
  app/alert_screen.py
  app/alerts.py
  app/assets/styles.css
  app/config.py
  app/graphs.py
  app/homepage.py
  app/main.py
  app/navbar.py
  app/risks.py
  app/utils.py
  requirements.txt
Labels: enhancement, topic: api
