Repository pyronear/pyro-platform, pull requests merged in 2022-06, with the labels that each got.

#75 ci: Updated funding from OpenCollective to Github
  .github/FUNDING.yml
Labels: enhancement, topic: build

#77 fix: Fixed the docker build of the platform
  app/alerts.py
  app/main.py
  requirements.txt
Labels: bug, topic: build, topic: api

#78 refactor: Cleaned project and added style verifications
  .flake8
  .github/validate_headers.py
  .github/workflows/docker.yml
  .github/workflows/main.yml
  .github/workflows/style.yml
  Makefile
  app/alert_screen.py
  app/alerts.py
  app/config.py
  app/dashboard_screen.py
  app/homepage.py
  app/main.py
  app/navbar.py
  app/risks.py
  app/services/__init__.py
  app/services/api.py
  app/utils.py
  pyproject.toml
  test/test_headers.py
Labels: enhancement, topic: build

#73 Fix: Filtering fire alerts to reduce platform loading time
  app/main.py
Labels: bug, enhancement
