Repository pyronear/pyro-platform, pull requests merged in 2023-11, with the labels that each got.

#118 Draw bbox
  app/main.py
  app/utils/alerts.py
Labels: type: enhancement

#123 ci: Removes dangling images on remote server
  .github/workflows/push.yml
Labels: type: bug, topic: build

#124 compose: updating prod compose file
  .github/workflows/push.yml
  docker-compose-prod.yml
Labels: topic: build

#126 ci: fix typo
  .github/workflows/push.yml
Labels: type: bug

#130 ci: adding right config file
  .github/workflows/push.yml
Labels: topic: build

#127 Fix bandit
  app/main.py
Labels: type: bug

#125 adaptative time
  app/utils/alerts.py
  pyproject.toml
Labels: type: bug, invalid

#131 ci: fix dev auto push
  .github/workflows/push.yml
  docker-compose-prod.yml
Labels: type: bug, topic: build
