Repository pyronear/pyro-platform, pull requests merged in 2023-10, with the labels that each got.

#111 display alerts from today
  app/main.py
  app/utils/alerts.py
Labels: type: enhancement

#114 ci: Adds continuous deployment through DockerHub
  .github/workflows/build.yml
  .github/workflows/push.yml
  Dockerfile
  Makefile
Labels: type: enhancement, topic: build

#116 ci: Fixes the deployment part of the CI job
  .github/workflows/push.yml
Labels: type: bug, topic: build

#117 ci: Removes legacy docker job
  .github/workflows/docker_publish.yaml
Labels: topic: build

#115 style: Switches to ruff for linting
  .flake8
  .github/workflows/style.yml
  .pre-commit-config.yaml
  Makefile
  app/components/navbar.py
  app/main.py
  app/pages/homepage.py
  app/pages/risks.py
  app/services/api.py
  app/utils/_utils.py
  app/utils/alerts.py
  pyproject.toml
Labels: type: enhancement

#112 Improove today alert filter
  app/main.py
  app/utils/alerts.py
Labels: type: bug, type: enhancement

#113 remove acknowledged alerts
  app/main.py
Labels: type: bug

#121 Fix n days
  app/utils/alerts.py
Labels: type: bug

#122 force alert list update
  app/main.py
  app/utils/alerts.py
Labels: type: bug

#119 dl current image
  app/main.py
  app/utils/alerts.py
Labels: type: enhancement
