Repository pyronear/pyro-platform, pull requests merged in 2025-02, with the labels that each got.

#187 keep alerts from today
  app/callbacks/data_callbacks.py
Labels: type: enhancement

#189 fix: Corrected typo in confirmation modal
  app/layouts/main_layout.py
Labels: Small

#188 Multiple bbox
  app/callbacks/display_callbacks.py
  app/pages/homepage.py
Labels: type: enhancement

#191 prevent empty
  app/callbacks/data_callbacks.py
Labels: type: bug

#193 Contributing section
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#194 Docs getting started
  README.md
Labels: documentation
