Repository pyronear/pyro-platform, pull requests merged in 2025-04, with the labels that each got.

#200 CI & Dependency Update
  .github/workflows/build.yml
  .github/workflows/push.yml
  .github/workflows/style.yml
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  Dockerfile
  Makefile
  app/callbacks/data_callbacks.py
  app/callbacks/display_callbacks.py
  app/index.py
  app/pages/cameras_status.py
  docker-compose-dev.yml
  docker-compose.yml
  pyproject.toml
Labels: type: bug

#199 Add Blinking page
  app/assets/css/style.css
  app/assets/images/alarm.svg
  app/callbacks/display_callbacks.py
  app/components/navbar.py
  app/index.py
  app/pages/blinking_alarm.py
Labels: type: enhancement, Small

#201 V2 history
  app/assets/images/alarm.svg
  app/assets/images/camera.svg
  app/callbacks/data_callbacks.py
  app/callbacks/display_callbacks.py
  app/components/navbar.py
Labels: type: enhancement
